In [31]:
# 말뭉치

In [3]:
text = 'You say goodbye and I say hello.'

In [5]:
text = text.lower()

In [7]:
text = text.replace('.', ' .')

In [8]:
text

'you say goodbye and i say hello .'

In [10]:
words =text.split(' ')

In [11]:
words

['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']

In [12]:
type(words)

list

In [14]:
word_to_id = {} # key : 단어, value : 단어ID
id_to_word = {} # key : 단어ID, value : 단어

for word in words:
    if word not in word_to_id:
        new_id = len(word_to_id)
        word_to_id[word] = new_id
        id_to_word[new_id] = word

In [15]:
id_to_word

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}

In [16]:
word_to_id

{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}

In [17]:
id_to_word[1]

'say'

In [18]:
word_to_id['hello']

5

In [21]:
import numpy as np
[word_to_id[w] for w in words]

[0, 1, 2, 3, 4, 1, 5, 6]

In [22]:
corpus = [word_to_id[w] for w in words]

In [23]:
np.array(corpus)

array([0, 1, 2, 3, 4, 1, 5, 6])

In [24]:
corpus = np.array(corpus)

In [25]:
corpus

array([0, 1, 2, 3, 4, 1, 5, 6])

In [27]:
def preprocess(text):
    text = text.lower()
    text = text.replace('.', ' .')
    words = text.split(' ')
    
    word_to_id={}
    id_to_word={}

    for word in words:
        if word not in word_to_id:
            new_id = len(word_to_id)
            word_to_id[word] = new_id

            id_to_word[new_id] = word

    corpus = np.array([word_to_id[w] for w in words])

    return corpus, word_to_id, id_to_word

In [28]:
text = 'You say goodbye and I say hello.'

In [29]:
preprocess(text)

(array([0, 1, 2, 3, 4, 1, 5, 6]),
 {'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6},
 {0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'})